### ISSUE TITLE
Prijava na bazo

### ISSUE THREAD

**Issue by jaanos** [tomazderca/OPB-umetnine#2]
Trenutno se na bazo prijavljata s podatki iz datoteke `user-data.txt`, brez katere ni mogoče pognati aplikacije. Da jo bo mogoče pognati brez poznavanja vajinih gesel za bazo, poskrbita, da se bo aplikacija prijavljala kot uporabnik `javnost`, ki mu bo seveda potrebno dodeliti ustrezne pravice na bazi.

Če želita imeti možnost poganjanja aplikacije z lastno prijavo na bazo, svetujem, da ubereta pristop iz campovski/beernburger#3 - lahko imata tudi `local_settings.py` na repozitoriju in v njej bereta iz `user-data.txt`.

Opažam še, da sta v a114b1a na repozitorij naložila geslo, ki je tako za vekomaj objavljeno na internetu. Če ga še nisi, svetujem, da ga @tomazderca zamenjaš.

Mimogrede, svetujem še, da poskrbita, da bo aplikacija delovala tudi na Binderju. Pomagata si lahko z [vzorčnim repozitorijem](https://github.com/jaanos/OPB-bottle) - skopirajta si mapo `binder` in popravita skripto `start` tako, da bo zagnala vajino aplikacijo (popravita predzadnjo vrstico); v `requirements.txt` pa dodajta še potrebne knjižnice (torej sam `django` in karkoli še potrebujeta). Pazita tudi, da poti v predlogah ne navajata neposredno, pač pa uporabita Djangovo funkcijo `url` - namesto npr. `/artists` torej uporabita `{% url 'homepage:artisti' %}` (ker se nanaša na pot v modulu `homepage`, podano s parametrom `name='artisti'`). Tako se bo generiral ustrezen URL (za delovanje na Binderju bo morda potrebno nekje v `settings.py` nastaviti osnovno pot na spremenljivko okolja `BOTTLE_ROOT`, podobno kot pri vzorcu - lahko jo tudi preimenujeta v skripti `start`).

**Comment by tomazderca** [comment]
Za Binder nisva popolnoma prepričana, kako ga naj usposobiva tako, da se bo aplikacija zaganjala. V primeru bottla, `start` pokliče `app_name.py` datoteko v kateri je `run` komanda, ki požene server. Je mišljeno, da se za django pokliče `manage.py`, ali se naredi posebej datoteko, ki vsebuje `run` komando? Sam sem poskusil tako, da sem v terminalu na Binderju ročno pognal `runserver`, ampak nisem znal presumeriti na samo stran.  Google mi za django, binder in docker ni bil pretirano v pomoč.

Prav tako tudi ne poznam najbolje os modula v pythonu, tako na nisem prepričan kako pravilno predelati `BASE_DIR` v djangotu tako, da bo kazal na `'BOTTLE_ROOT'`. 

Hvala lepa za pomoč.
